### ISSUE TITLE
 java.lang.NoClassDefFoundError: android/os/PersistableBundle crash

### ISSUE THREAD

**Issue by vad-zuev** [beworker/tinybus#40] opened 2015-09-30 08:51 UTC
After some recent Play Services update this crash has become very common for any app using any kind of Event Bus implementation on pre-21 devices. Happens when trying to call `register(Obj)`. 
The only solution I've seen so far is not using anything containing the `PersistableBundle`, which I don't use anyway and still have this issue.
Do you have any ideas on that?

**Comment by beworker** [comment] 2015-09-30 11:25
I don't use PersistableBundle in the code at all. Do you have a stacktrace or the exception?

**Comment by vad-zuev** [comment] 2015-09-30 11:42
I'm aware of the fact that you don't use it. It is somehow related to some parts of the Android SDK, my stack trace is basically the same as posted here https://github.com/square/otto/issues/139 
After some googling I realized that many apps that use any kind of some event bus are affected, but I haven't seen any proper solution so far

**Comment by beworker** [comment] 2015-09-30 11:54
Ah, I see. Thanks for letting me know. I'll keep the issue open until I can execute tests on a Marshmallow device.

**Comment by beworker** [comment] 2015-10-08 20:29
I was not able to reproduce the issue on a 6.0 device. That's why closing.

**Closed by beworker** 2015-10-08 20:29 UTC
Labels: TODO
